name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install toolchain
        uses: kazutoiris/yosys-action@v1

      - name: Run prove & cover
        run:
          make prove && make cover
